spring.application.name=meetly

spring.datasource.url=jdbc:postgresql://localhost:5433/meetly
spring.datasource.username=meetly
spring.datasource.password=meetly
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info,metrics

server.port=8080