spring.application.name=meetly

spring.datasource.url=jdbc:postgresql://localhost:5433/meetly
spring.datasource.username=meetly
spring.datasource.password=meetly
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info,metrics

server.port=8080

# AWS 
aws.region=ap-southeast-1
aws.cognito.user-pool-id=ap-southeast-1_u415xYkyy
aws.cognito.client-id=2hlen42452as040k5qsd6e22o2
aws.cognito.client-secret=p13c3updgbgd61dk4c62b0op1ibhd40num1ahv5srdpoe79urdu
aws.cognito.auth-flow=USER_PASSWORD_AUTH